//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineDocBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class GENDER
    {
        public int GENDER_ID { get; set; }
        public string GENDER_NAME { get; set; }
    }
}
