//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineDocBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int USER_ID { get; set; }
        public string USER_FULL_NAME { get; set; }
        public Nullable<int> USER_MOBILE_NUMBER { get; set; }
        public string USER_EMAIL_ADDRESS { get; set; }
        public string USER_ZIP_CODE { get; set; }
        public int USER_GENDER_ID { get; set; }
        public Nullable<int> USER_NID { get; set; }
        public string USER_PROFILE_PICTURE_URL { get; set; }
        public Nullable<System.DateTime> USER_DOB { get; set; }
        public string USER_AGE_STATUS { get; set; }
        public Nullable<System.DateTime> USER_CREATED_DATE { get; set; }
        public Nullable<System.DateTime> USER_EDITED_DATE { get; set; }
        public Nullable<bool> USER_IS_VARIFIED { get; set; }
        public string USER_HASH_PASSWORD { get; set; }
    }
}
